### ISSUE TITLE
getFloatingSpeciesIds() returns a single string

### ISSUE THREAD

**Issue by really-lilly** [sys-bio/RoadRunner.jl#1]
The function getFloatingSpeciesIds() returns a single string (eg. "S1 S2 S3 S4") instead of a Vector{String}. 

I quickly fixed this in my version by making the getFloatingSpeciesIds() function look more like the getReactionIds() functions:

function getFloatingSpeciesIds(rr::Ptr{Nothing})
    data = ccall(dlsym(rrlib, :getFloatingSpeciesIds), cdecl, Ptr{RRStringArray}, (Ptr{Nothing},), rr)
    num_Ids = getNumberOfFloatingSpecies(rr)
    specIds = String[]
    try
      for i = 1:num_Ids
        push!(specIds, getStringElement(data, i - 1))
      end
    catch e
      throw(e)
    finally
      freeStringArray(data)
    end
    return specIds
end

**Comment by SunnyXu** [comment]
double checked
